/** Single registry of TanStack Query keys, so invalidation never guesses. */
export const queryKeys = {
  session: ['session'] as const,
  health: ['system', 'health'] as const,
  appInfo: ['system', 'app-info'] as const,
  aiStatus: ['ai', 'status'] as const,
  followUps: (query: Record<string, unknown> = {}) => ['follow-ups', query] as const,
  followUpsAll: ['follow-ups'] as const,
  followUpRules: ['follow-ups', 'rules'] as const,
  dashboard: (query: Record<string, unknown> = {}) => ['reports', 'dashboard', query] as const,
  performance: (query: Record<string, unknown> = {}) => ['reports', 'performance', query] as const,
  expenses: (query: Record<string, unknown> = {}) => ['expenses', 'list', query] as const,
  expenseSummary: (query: Record<string, unknown> = {}) => ['expenses', 'summary', query] as const,
  expenseCategories: ['expenses', 'categories'] as const,
  expensesAll: ['expenses'] as const,
  invoices: (query: Record<string, unknown> = {}) => ['invoices', query] as const,
  invoicesAll: ['invoices'] as const,
  invoice: (id: string) => ['invoices', id] as const,
  smtp: ['settings', 'smtp'] as const,
  company: ['settings', 'company'] as const,
  template: (kind: string) => ['settings', 'templates', kind] as const,
  notificationLog: ['settings', 'notifications'] as const,
  staff: ['staff'] as const,
  users: ['users'] as const,
  audit: (query: Record<string, unknown> = {}) => ['audit', query] as const,
  leads: (query: Record<string, unknown> = {}) => ['leads', query] as const,
  leadsAll: ['leads'] as const,
  lead: (id: string) => ['leads', id, 'detail'] as const,
  leadActivities: (id: string) => ['leads', id, 'activities'] as const,
  leadDuplicates: (params: Record<string, unknown>) => ['leads', 'duplicates', params] as const,
  leadProposals: (leadId: string) => ['leads', leadId, 'proposals'] as const,
  proposal: (id: string) => ['proposals', id] as const,
  proposals: (query: Record<string, unknown> = {}) => ['proposals', 'list', query] as const,
  payments: (query: Record<string, unknown> = {}) => ['payments', query] as const,
  customers: (query: Record<string, unknown> = {}) => ['customers', query] as const,
  customer: (id: string) => ['customers', id, 'detail'] as const,
  conversations: (search = '') => ['conversations', { search }] as const,
  conversationsAll: ['conversations'] as const,
  conversation: (id: string) => ['conversations', id, 'detail'] as const,
  quotes: (conversationId: string) => ['conversations', conversationId, 'quotes'] as const,
  messages: (conversationId: string) => ['conversations', conversationId, 'messages'] as const,
};
